import img1 from "../src/assets/images/car-1.jpg";
import img2 from "../src/assets/images/car-2.jpg";
import img3 from "../src/assets/images/car-3.jpg";
import img4 from "../src/assets/images/car-4.jpg";
import img5 from "../src/assets/images/car-5.jpg";
import img6 from "../src/assets/images/car-6.jpg";

export default [
  {
    id: "1",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "2",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "3",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "4",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "5",
    name: "BMW 4 Series GTI",
    image: img5,
    year: "2021",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.6km",
    type: "Automatic",
    price: "$530",
  },
  {
    id: "6",
    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "7",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "8",

    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "9",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "10",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "11",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "12",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "13",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "14",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "15",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "16",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "17",
    name: "BMW 4 Series GTI",
    image: img5,
    year: "2021",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.6km",
    type: "Automatic",
    price: "$530",
  },
  {
    id: "18",
    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "19",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "20",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "21",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "22",
    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "23",
    name: "BMW 4 Series GTI",
    image: img5,
    year: "2021",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.6km",
    type: "Automatic",
    price: "$530",
  },
  {
    id: "24",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "25",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "26",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "27",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "28",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "29",
    name: "BMW 4 Series GTI",
    image: img5,
    year: "2021",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.6km",
    type: "Automatic",
    price: "$530",
  },
  {
    id: "30",
    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "31",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "32",
    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "33",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "34",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "35",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "36",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "37",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "38",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "39",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "40",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "41",
    name: "BMW 4 Series GTI",
    image: img5,
    year: "2021",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.6km",
    type: "Automatic",
    price: "$530",
  },
  {
    id: "42",
    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "43",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "44",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "45",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "46",
    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "47",
    name: "BMW 4 Series GTI",
    image: img5,
    year: "2021",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.6km",
    type: "Automatic",
    price: "$530",
  },
  {
    id: "48",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "49",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "50",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "51",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "52",
    name: "BMW 4 Series GTI",
    image: img5,
    year: "2021",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.6km",
    type: "Automatic",
    price: "$530",
  },
  {
    id: "53",
    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "54",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "55",

    name: "BMW 4 Series",
    image: img6,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.2km",
    type: "Automatic",
    price: "$490",
  },
  {
    id: "56",
    name: "BMW 3 Series",
    image: img2,
    year: "2019",
    capacity: "4 people",
    mode: "Gasoline",
    average: "8.2km",
    type: "Automatic",
    price: "$350",
  },
  {
    id: "57",
    name: "Volkswagen T-Cross",
    image: img3,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "5.3km",
    type: "Automatic",
    price: "$400",
  },
  {
    id: "58",
    name: "Cadillac Escalade",
    image: img4,
    year: "2020",
    capacity: "4 people",
    mode: "Gasoline",
    average: "7.7km",
    type: "Automatic",
    price: "$620",
  },
  {
    id: "59",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
  {
    id: "60",
    name: "Toyota RAV4",
    image: img1,
    year: "2021",
    capacity: "4 people",
    mode: "Hybrid",
    average: "6.1km",
    type: "Automatic",
    price: "$440",
  },
];
